show tables;
-- Basic Problems --
-- 1.List all unique cities where customers are located.
SELECT DISTINCT customer_city
FROM customers
order by customer_city;
-- 2.Count the number of orders placed in 2017.
SELECT COUNT(*) 
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2017;
-- 3.Find the total sales per category.
SELECT
    p.product_category,
    SUM(oi.price) AS total_sales
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
GROUP BY p.product_category
ORDER BY total_sales DESC;

-- 4.Calculate the percentage of orders that were paid in installments.
SELECT 
    ROUND(
        (SUM(CASE WHEN payment_installments > 1 THEN 1 ELSE 0 END) / COUNT(*)) * 100,
    2) AS percent_installment
FROM payments;
-- 5.Count the number of customers from each state.
SELECT 
    customer_state,
    COUNT(DISTINCT customer_id) AS num_customers
FROM customers
GROUP BY customer_state
ORDER BY num_customers DESC;
-- Intermediate Problems --
-- 1.Calculate the number of orders per month in 2018.
SELECT
    DATE_FORMAT(order_purchase_timestamp, '%Y-%m') AS month,
    COUNT(*) AS num_orders
FROM orders
WHERE DATE_FORMAT(order_purchase_timestamp, '%Y') = '2018'
GROUP BY DATE_FORMAT(order_purchase_timestamp, '%Y-%m')
ORDER BY month;
-- 2.Find the average number of products per order, grouped by customer city.
SELECT 
    c.customer_city AS customer_city,
    AVG(t.product_count) AS avg_products_per_order
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN (
    SELECT 
        order_id,
        COUNT(*) AS product_count
    FROM order_items
    GROUP BY order_id
) AS t
    ON o.order_id = t.order_id
GROUP BY c.customer_city
ORDER BY avg_products_per_order DESC;
-- 3.Calculate the percentage of total revenue contributed by each product category.
SELECT 
    p.product_category,
    ROUND(
        (SUM(oi.price) / (SELECT SUM(price) FROM order_items)) * 100,
        2
    ) AS revenue_percent
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
GROUP BY p.product_category
ORDER BY revenue_percent DESC;
-- 4.Identify the correlation between product price and the number of times a product has been purchased.
SELECT
    ROUND(
        (
            (COUNT(*) * SUM(avg_price * purchase_count))
            - (SUM(avg_price) * SUM(purchase_count))
        ) /
        (
            SQRT(
                (COUNT(*) * SUM(avg_price * avg_price)) - (SUM(avg_price) * SUM(avg_price))
            ) *
            SQRT(
                (COUNT(*) * SUM(purchase_count * purchase_count)) - (SUM(purchase_count) * SUM(purchase_count))
            )
        )
    , 2) AS correlation
FROM (
    SELECT
        p.product_id,
        AVG(oi.price) AS avg_price,
        COUNT(oi.order_id) AS purchase_count
    FROM products p
    JOIN order_items oi 
        ON p.product_id = oi.product_id
    GROUP BY p.product_id
) AS t;
-- 5.Calculate the total revenue generated by each seller, and rank them by revenue.
SELECT
    seller_id,
    SUM(price) AS price,
    SUM(freight_value) AS freight_value,
    SUM(price + freight_value) AS total_revenue,
    RANK() OVER (ORDER BY SUM(price + freight_value) DESC) AS revenue_rank
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC;

-- Advanced Probblems --
-- 1.Calculate the moving average of order values for each customer over their order history.
SELECT
    ot.order_id,
    ot.customer_id,
    ot.order_purchase_timestamp,
    ot.payment_value,
    
    AVG(ot.payment_value) OVER (
        PARTITION BY ot.customer_id
        ORDER BY ot.order_purchase_timestamp
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS moving_avg_order_value

FROM (
    SELECT 
        p.order_id,
        SUM(p.payment_value) AS payment_value,
        o.customer_id,
        o.order_purchase_timestamp
    FROM payments p
    JOIN orders o 
        ON p.order_id = o.order_id
    GROUP BY 
        p.order_id, 
        o.customer_id, 
        o.order_purchase_timestamp
) AS ot
ORDER BY 
    ot.customer_id,
    ot.order_purchase_timestamp;
    -- 2.Calculate the cumulative sales per month for each year.
    SELECT 
    order_year,
    order_month,
    monthly_payment,
    SUM(monthly_payment) OVER (PARTITION BY order_year ORDER BY order_month) AS cumulative_sales
FROM (
    SELECT 
        YEAR(o.order_purchase_timestamp) AS order_year,
        MONTH(o.order_purchase_timestamp) AS order_month,
        SUM(p.payment_value) AS monthly_payment
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    GROUP BY order_year, order_month
) AS monthly_data
ORDER BY order_year, order_month;
-- 3.Calculate the year-over-year growth rate of total sales.
SELECT
    order_year,
    total_sales,
    LAG(total_sales) OVER (ORDER BY order_year) AS prev_year_sales,
    ROUND(
        (total_sales - LAG(total_sales) OVER (ORDER BY order_year)) 
        / LAG(total_sales) OVER (ORDER BY order_year) * 100, 2
    ) AS yoy_growth_percent
FROM (
    SELECT 
        YEAR(o.order_purchase_timestamp) AS order_year,
        SUM(p.payment_value) AS total_sales
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    GROUP BY order_year
) AS yearly_sales
ORDER BY order_year;
-- 4.Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase.
WITH first_purchase AS (
    SELECT 
        customer_id,
        MIN(order_purchase_timestamp) AS first_purchase_date
    FROM orders
    GROUP BY customer_id
),
repeat_purchase AS (
    SELECT 
        o.customer_id,
        f.first_purchase_date,
        o.order_purchase_timestamp AS next_purchase_date
    FROM orders o
    JOIN first_purchase f ON o.customer_id = f.customer_id
    WHERE o.order_purchase_timestamp > f.first_purchase_date
      AND o.order_purchase_timestamp <= DATE_ADD(f.first_purchase_date, INTERVAL 6 MONTH)
)
SELECT 
    ROUND(
        (SELECT COUNT(DISTINCT customer_id) FROM repeat_purchase) 
        / (SELECT COUNT(DISTINCT customer_id) FROM orders) * 100, 2
    ) AS retention_rate_percent;
    -- 5.Identify the top 3 customers who spent the most money in each year.
    WITH yearly_customer_sales AS (
    SELECT
        o.customer_id,
        YEAR(o.order_purchase_timestamp) AS order_year,
        SUM(p.payment_value) AS total_spent
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    GROUP BY o.customer_id, order_year
)
SELECT
    customer_id,
    order_year,
    total_spent
FROM (
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY order_year ORDER BY total_spent DESC) AS rnk
    FROM yearly_customer_sales
) AS ranked_sales
WHERE rnk <= 3
ORDER BY order_year, rnk;






