# -*- coding: utf-8 -*-
"""retail_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBSZUceoUPsh5b4POAkiQznuBjx0M0nY
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files

uploaded = files.upload()

customers = pd.read_csv("customers.csv")

orders = pd.read_csv("orders.csv")

order_items = pd.read_csv("order_items.csv")

products = pd.read_csv("products.csv")

payments = pd.read_csv('payments.csv')

# Load only sellers with encoding fix
sellers = pd.read_csv('sellers.csv', encoding='latin1')

geolocation = pd.read_csv('geolocation.csv')

# Combine all datasets into a dictionary for easy checking
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "payments": payments,
    "sellers": sellers,
    "geolocation": geolocation
}

# Display info and missing values
for name, df in datasets.items():
    print(f"\n🔍 {name.upper()} DATA OVERVIEW")
    print(df.info())
    print(f"\nMissing values:\n{df.isnull().sum()}")
    print("-" * 60)

orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'], errors='coerce')

orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'], errors='coerce')

orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'], errors='coerce')

orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'], errors='coerce')

orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'], errors='coerce')

orders.info()

for name, df in [("customers",customers),("orders",orders),("order_items",order_items),("products",products),("payments",payments),("sellers",sellers),("geolocation",geolocation)]:
    print(name, "=>", list(df.columns))

"""**Basic Questions**"""

# 1. List all unique cities where customers are located.
unique_cities = customers['customer_city'].unique()
print("Unique cities where customers are located:")
print(unique_cities)

# 2.Count the number of orders placed in 2017.
orders_2017 = orders[orders['order_purchase_timestamp'].dt.year == 2017]
num_orders_2017 = len(orders_2017)

print(f"Total orders placed in 2017: {num_orders_2017}")

# 3. Find the total sales per category.
sales_per_category = order_items.merge(products, on='product_id')

total_sales_category = (
    sales_per_category
    .groupby('product_category')['price']
    .sum()
    .reset_index()
    .sort_values(by='price', ascending=False)
)

total_sales_category.columns = ['Product Category', 'Total Sales']

print(total_sales_category.head(5))

# 4.Calculate the percentage of orders that were paid in installments.
total_orders = len(payments)

installment_orders = len(payments[payments['payment_installments'] > 1])

percentage_installments = (installment_orders / total_orders) * 100

print(f"Percentage of orders paid in installments: {percentage_installments:.2f}%")

# 5.Count the number of customers from each state.
customers_per_state = customers['customer_state'].value_counts().reset_index()

customers_per_state.columns = ['state', 'customer_count']

print(customers_per_state)

plt.figure(figsize=(10,5))
plt.bar(customers_per_state['state'], customers_per_state['customer_count'])
plt.title('Number of Customers by State')
plt.xlabel('State')
plt.ylabel('Number of Customers')
plt.xticks(rotation=45)
plt.show()

"""**Intermediate Questions**"""

# 1.Calculate the number of orders per month in 2018.
orders['year'] = orders['order_purchase_timestamp'].dt.year

orders['month'] = orders['order_purchase_timestamp'].dt.month_name()

orders_2018 = orders[orders['year'] == 2018]

orders_per_month_2018 = orders_2018.groupby('month')['order_id'].count().reindex([
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
])

print("🗓 Orders per month in 2018:")
print(orders_per_month_2018)

orders_per_month_2018.plot(kind='bar', figsize=(10, 5), color='yellow')
plt.title("Number of Orders per Month in 2018")
plt.xlabel("Month")
plt.ylabel("Number of Orders")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 2.Find the average number of products per order, grouped by customer city.
orders_customers = pd.merge(orders, customers, on='customer_id', how='inner')

orders_items = pd.merge(orders_customers, order_items, on='order_id', how='inner')

products_per_order = orders_items.groupby(['customer_city', 'order_id']).size().reset_index(name='num_products')

avg_products_per_city = products_per_order.groupby('customer_city')['num_products'].mean().sort_values(ascending=False)

print("Average number of products per order grouped by city:")
print(avg_products_per_city.head(10))

avg_products_per_city.head(10).plot(kind='bar', figsize=(10,5), color='orange')
plt.title("Average Number of Products per Order by City (Top 10)")
plt.xlabel("Customer City")
plt.ylabel("Average Number of Products")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 3. Calculate the percentage of total revenue contributed by each product category.
merged_data = pd.merge(order_items, products, on='product_id', how='inner')

category_revenue = merged_data.groupby('product_category')['price'].sum().reset_index()

total_revenue = category_revenue['price'].sum()

category_revenue['revenue_percentage'] = (category_revenue['price'] / total_revenue) * 100

category_revenue = category_revenue.sort_values(by='revenue_percentage', ascending=False)

print("Percentage of Total Revenue by Product Category:")
print(category_revenue.head(10))

plt.figure(figsize=(10, 6))
plt.bar(category_revenue['product_category'].head(10), category_revenue['revenue_percentage'].head(10), color='lightgreen')
plt.title("Top 10 Product Categories by Revenue Contribution (%)")
plt.xlabel("Product Category")
plt.ylabel("Revenue Contribution (%)")
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 4.. Identify the correlation between product price and the number of times a product has been purchased.
product_purchase_counts = order_items.groupby('product_id').size().reset_index(name='purchase_count')

product_avg_price = order_items.groupby('product_id')['price'].mean().reset_index(name='avg_price')

product_stats = pd.merge(product_purchase_counts, product_avg_price, on='product_id')

correlation = product_stats['avg_price'].corr(product_stats['purchase_count'])

print(f"Correlation between product price and purchase count: {correlation:.2f}")

plt.figure(figsize=(8,5))
plt.scatter(product_stats['avg_price'], product_stats['purchase_count'], alpha=0.5, color='purple')
plt.title('Correlation between Product Price and Purchase Frequency')
plt.xlabel('Average Product Price')
plt.ylabel('Number of Purchases')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# 5.Calculate the total revenue generated by each seller, and rank them by revenue.
seller_revenue = order_items.groupby('seller_id')[['price', 'freight_value']].sum()

seller_revenue['total_revenue'] = seller_revenue['price'] + seller_revenue['freight_value']

seller_revenue = seller_revenue.sort_values(by='total_revenue', ascending=False).reset_index()

seller_revenue['revenue_rank'] = seller_revenue['total_revenue'].rank(method='dense', ascending=False).astype(int)

print(seller_revenue.head(5))

plt.figure(figsize=(10,5))
plt.bar(seller_revenue['seller_id'][:10], seller_revenue['total_revenue'][:10], color='red')
plt.title('Top 10 Sellers by Total Revenue')
plt.xlabel('Seller ID')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""**Advanced Questions**"""

# 1. Calculate the moving average of order values for each customer over their order history.
order_totals = (
    payments
    .groupby('order_id')['payment_value']
    .sum()
    .reset_index()
)

order_totals = order_totals.merge(
    orders[['order_id', 'customer_id', 'order_purchase_timestamp']],
    on='order_id',
    how='left'
)

order_totals = order_totals.sort_values(['customer_id', 'order_purchase_timestamp'])

order_totals['moving_avg_order_value'] = (
    order_totals
    .groupby('customer_id')['payment_value']
    .expanding()
    .mean()
    .reset_index(level=0, drop=True)
)

order_totals['payment_value'] = order_totals['payment_value'].round(2)
order_totals['moving_avg_order_value'] = order_totals['moving_avg_order_value'].round(2)

print(order_totals.head(5))

cid = order_totals['customer_id'].iloc[0]

df = order_totals[order_totals['customer_id'] == cid]

plt.figure(figsize=(10,5))
plt.plot(df['order_purchase_timestamp'], df['moving_avg_order_value'])

plt.xlabel("Order Date")
plt.ylabel("Moving Avg Order Value")
plt.title(f"Moving Avg Order Value for Customer {cid}")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 2.Calculate the cumulative sales per month for each year.
sales_data = pd.merge(orders, payments, on='order_id', how='inner')

sales_data['year'] = sales_data['order_purchase_timestamp'].dt.year

sales_data['month'] = sales_data['order_purchase_timestamp'].dt.month

monthly_sales = (
    sales_data.groupby(['year', 'month'])['payment_value']
    .sum()
    .reset_index()
    .sort_values(['year', 'month'])
)

monthly_sales['cumulative_sales'] = (
    monthly_sales.groupby('year')['payment_value'].cumsum()
)

print(monthly_sales.head(5))

plt.figure(figsize=(10,6))
for year in monthly_sales['year'].unique():
    subset = monthly_sales[monthly_sales['year'] == year]
    plt.plot(subset['month'], subset['cumulative_sales'], marker='o', label=f'{year}')

plt.title('Cumulative Monthly Sales per Year')
plt.xlabel('Month')
plt.ylabel('Cumulative Sales (₹)')
plt.legend()
plt.grid(True)
plt.show()

# 3.Calculate the year-over-year growth rate of total sales.
sales_yoy = pd.merge(orders, payments, on='order_id', how='inner')

sales_yoy['order_purchase_timestamp'] = pd.to_datetime(sales_yoy['order_purchase_timestamp'])

sales_yoy['year'] = sales_yoy['order_purchase_timestamp'].dt.year

annual_sales = (
    sales_yoy.groupby('year')['payment_value']
    .sum()
    .reset_index()
    .sort_values('year')
)

annual_sales['yoy_growth_%'] = annual_sales['payment_value'].pct_change() * 100

print(annual_sales)

plt.figure(figsize=(8,5))
plt.bar(annual_sales['year'], annual_sales['yoy_growth_%'])
plt.title('Year-over-Year Growth Rate of Total Sales')
plt.xlabel('Year')
plt.ylabel('Growth Rate (%)')
plt.grid(True, axis='y')
plt.show()

# 4. Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase.
customer_orders = (
    orders.sort_values(['customer_id', 'order_purchase_timestamp'])
    .groupby('customer_id')['order_purchase_timestamp']
    .apply(list)
    .reset_index()
)

def made_repeat_purchase_within_6_months(dates):
    if len(dates) < 2:
        return False
    first_order = dates[0]
    for next_order in dates[1:]:
        if (next_order - first_order).days <= 180:
            return True
    return False

customer_orders['retained'] = customer_orders['order_purchase_timestamp'].apply(
    made_repeat_purchase_within_6_months
)

retention_rate = (
    customer_orders['retained'].sum() / len(customer_orders)
) * 100

print(f"Customer Retention Rate (within 6 months): {retention_rate:.2f}%")

total_customers = 99441
repeat_customers = 0
one_time_customers = total_customers - repeat_customers

labels = ['One-time Customers', 'Repeat Customers']
sizes = [one_time_customers, repeat_customers]
colors = ['#66b3ff', '#99ff99']
explode = (0.05, 0.05)

plt.figure(figsize=(6,6))
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%',
        startangle=140, explode=explode, shadow=True, textprops={'fontsize': 12})
plt.title('Customer Retention Rate (Within 6 Months)', fontsize=14, fontweight='bold')
plt.show()

# 5. Identify the top 3 customers who spent the most money in each year.
customer_spending = pd.merge(orders, payments, on='order_id', how='inner')

customer_spending['year'] = pd.to_datetime(customer_spending['order_purchase_timestamp']).dt.year

total_spend = (
    customer_spending.groupby(['year', 'customer_id'])['payment_value']
    .sum()
    .reset_index()
)

total_spend['rank'] = total_spend.groupby('year')['payment_value'].rank(method='dense', ascending=False)

top3_customers = total_spend[total_spend['rank'] <= 3].sort_values(['year', 'rank'])

print(top3_customers)

for year in sorted(top3_customers['year'].unique()):
    data = top3_customers[top3_customers['year'] == year]
    if data.empty:
           continue

plt.figure(figsize=(7,5))
plt.bar(data['customer_id'], data['payment_value'], color='cornflowerblue', edgecolor='black')
plt.title(f'Top 3 Customers by Spending - {year}', fontsize=14, fontweight='bold')
plt.xlabel('Customer ID', fontsize=12)
plt.ylabel('Total Spending', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""**Conclusions**
Total customers analyzed: 99,441 with zero repeat purchases within 6 months.

Customer concentration is highest in SP and RJ states.

Total payments in 2017: 7,249,746; 2018: 8,699,763, showing ~20% YoY growth.

Orders peak in mid-year months, indicating seasonal trends.

Top-selling categories by revenue: Perfumery, Sport & Leisure, and Babies.

Higher-priced products are moderately purchased, showing balance between price and demand.

Seller revenue highlights top-performing sellers driving maximum revenue.

Top 3 customers per year identified for personalized engagement.

**Recommendations**
Introduce loyalty programs and repeat purchase incentives to improve retention.

Focus inventory and marketing on high-revenue categories to increase profit.

Collaborate and incentivize top-performing sellers; support underperforming sellers.

Target regions with high customer concentration for marketing campaigns.

Use seasonal trends to plan promotions and boost sales.

Create VIP programs and send exclusive offers to top-spending customers.
"""